version: '2.4'

services:

    worker-situator:
        container_name: worker-situator
        environment:
            - VIRTUAL_HOST=api.${DOCKERS_APP_DOMAIN}
            - PHP_VERSION_SHORT=8.2
            - PHPINI_OPEN_BASEDIR=/app
            - PHPFPM_LOG_LEVEL=debug
            - VIRTUAL_PORT=80
            - ALLOW_URL_FOPEN=On
            - LOG_FILE=api.log
            - PUBLIC_ROOT=public
            - NGINX_POLICY=Content-Security-Policy-Report-Only
            - NGINX_POLICY_VALUE=default-src self;
            - STATIC_URL=/static
            - STATIC_PATH=/app/static
        image: ghcr.io/parisprobr/server-tools:php-8.2
        hostname: api.${DOCKERS_APP_DOMAIN}
        depends_on:
            - worker-situator-db
            - nginx-proxy
            - composer-worker-situator
        command: bash -c 'chmod +x /root/scripts/start.sh; /root/scripts/start.sh'
        restart: always
        volumes:
            - ../worker-situator/:/app
            - ../worker-situator/storage/logs:/var/log/export
            - ../worker-situator/docker/scripts/start.sh:/root/scripts/start.sh
        env_file:
            - ../worker-situator/.env

    composer-worker-situator:
        image: composer:2.5
        network_mode: host
        container_name: composer-worker-situator
        user: "${UID}:${UID}"
        command: composer install
        volumes:
            - ../worker-situator/:/app
            - ${HOME}:${HOME}
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro

    worker-situator-db:
        container_name: worker-situator-db
        environment:
            MYSQL_ROOT_PASSWORD: kK123KFTah78dAiv
            MYSQL_DATABASE: workersituator
            MYSQL_USER: workersituator
            MYSQL_PASSWORD: kK123KFTah78dAiv
        image: mysql:5.7
        volumes:
            - ../worker-situator/database/mysql:/var/lib/mysql
        env_file: ../worker-situator/.env

    phpmyadmin-es:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-es
        restart: on-failure
        links:
            - worker-situator-db
        environment:
            PMA_HOSTS: worker-situator-db
            VIRTUAL_HOST: mysql.${DOCKERS_APP_DOMAIN}
        depends_on:
            - worker-situator-db
